<a href="https://colab.research.google.com/github/majorquev/DBDC_202507_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto).
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [1]:
LETTERS
letters

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [2]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
l1 <- list(num = 1:5,
           letra = "X",
           pl = c("hola", "buenas", "noches"),
           mat = diag(1:5),
           lista = list(a = as.Date("2025-07-09"),
                        b = LETTERS))

In [3]:
l1

$num
[1] 1 2 3 4 5

$letra
[1] "X"

$pl
[1] "hola"   "buenas" "noches"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$lista
$lista$a
[1] "2025-07-09"

$lista$b
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [4]:
# estructura
str(l1)

List of 5
 $ num  : int [1:5] 1 2 3 4 5
 $ letra: chr "X"
 $ pl   : chr [1:3] "hola" "buenas" "noches"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...


In [5]:
# atributos básicos
length(l1)
names(l1)

[1] 5

[1] "num"   "letra" "pl"    "mat"   "lista"

In [6]:
# Podemos guardar los objetos en slots con nombres (o no)
l2 <- list(1:4, "X", diag(1:2))

In [7]:
str(l2)

List of 3
 $ : int [1:4] 1 2 3 4
 $ : chr "X"
 $ : int [1:2, 1:2] 1 0 0 2


In [8]:
names(l2) <- c("n1","n2","n3")

In [9]:
str(l2)

List of 3
 $ n1: int [1:4] 1 2 3 4
 $ n2: chr "X"
 $ n3: int [1:2, 1:2] 1 0 0 2


In [10]:
# Podemos combinar listas
l3 <- c(l1,l2)
str(l3)

List of 8
 $ num  : int [1:5] 1 2 3 4 5
 $ letra: chr "X"
 $ pl   : chr [1:3] "hola" "buenas" "noches"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...
 $ n1   : int [1:4] 1 2 3 4
 $ n2   : chr "X"
 $ n3   : int [1:2, 1:2] 1 0 0 2


In [11]:
# Acceso mediante posición
l3[3]

$pl
[1] "hola"   "buenas" "noches"

In [ ]:
class(l3)
class(l3[3])

[1] "list"

[1] "list"

In [ ]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l3[3]



$pl
[1] "hola"   "buenas" "noches"

In [12]:
l3[[3]]

[1] "hola"   "buenas" "noches"

In [13]:
class(l3[[3]])

[1] "character"

In [14]:
l3[[3]][2]

[1] "buenas"

In [15]:
str(l3)

List of 8
 $ num  : int [1:5] 1 2 3 4 5
 $ letra: chr "X"
 $ pl   : chr [1:3] "hola" "buenas" "noches"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...
 $ n1   : int [1:4] 1 2 3 4
 $ n2   : chr "X"
 $ n3   : int [1:2, 1:2] 1 0 0 2


In [16]:
# de la lista l3[[5]], quieo el vector que está en el slot llamado "b" (segundo elemento)
l3[5]# Recordar que retorna una lista (de largo 1) con lo que está adentro

$lista
$lista$a
[1] "2025-07-09"

$lista$b
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [17]:
l3[[5]]# Esto es el elmento que está en la posición 5  (que en particular, en este caso, es un lista tbn)


$a
[1] "2025-07-09"

$b
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [19]:
str(l3[5])

List of 1
 $ lista:List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...


In [18]:
str(l3[[5]])

List of 2
 $ a: Date[1:1], format: "2025-07-09"
 $ b: chr [1:26] "A" "B" "C" "D" ...


In [20]:
l3[[5]][2] # una lista con el vector b

$b
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [21]:
l3[[5]][[2]] # El vector b

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [22]:
str(l3)

List of 8
 $ num  : int [1:5] 1 2 3 4 5
 $ letra: chr "X"
 $ pl   : chr [1:3] "hola" "buenas" "noches"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...
 $ n1   : int [1:4] 1 2 3 4
 $ n2   : chr "X"
 $ n3   : int [1:2, 1:2] 1 0 0 2


In [23]:
# Acceso mediante nombre
l3[["lista"]][["b"]] # El vector b


[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [26]:
# acceso vía "$"
l3$mat
#es equivalente a
l3[["mat"]]
l3[[4]]




[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [29]:
str(l3)

List of 8
 $ num  : int [1:5] 1 2 3 4 5
 $ letra: chr "X"
 $ pl   : chr [1:3] "hola" "buenas" "noches"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...
 $ n1   : int [1:4] 1 2 3 4
 $ n2   : chr "X"
 $ n3   : int [1:2, 1:2] 1 0 0 2


In [28]:
l3$lista$b
#Esto esequivalente a
l3[[5]][[2]]
l3[["lista"]][["b"]]

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [33]:
# para saber el largo de la lista/vector
length(l3)
# Para obtener los nombres de la lista
names(l3)
# si quisiéramos renombrar los slots:
names(l3)[4] <- "matriz"

[1] 8

[1] "num"   "letra" "pl"    "mat"   "lista" "n1"    "n2"    "n3"

In [34]:
names(l3)

[1] "num"    "letra"  "pl"     "matriz" "lista"  "n1"     "n2"     "n3"

In [35]:
str(l3)

List of 8
 $ num   : int [1:5] 1 2 3 4 5
 $ letra : chr "X"
 $ pl    : chr [1:3] "hola" "buenas" "noches"
 $ matriz: int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista :List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...
 $ n1    : int [1:4] 1 2 3 4
 $ n2    : chr "X"
 $ n3    : int [1:2, 1:2] 1 0 0 2


In [37]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando, o
l3[["values_lgl"]] <- c(T,F,T,T)






In [38]:
str(l3)

List of 9
 $ num       : int [1:5] 1 2 3 4 5
 $ letra     : chr "X"
 $ pl        : chr [1:3] "hola" "buenas" "noches"
 $ matriz    : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista     :List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...
 $ n1        : int [1:4] 1 2 3 4
 $ n2        : chr "X"
 $ n3        : int [1:2, 1:2] 1 0 0 2
 $ values_lgl: logi [1:4] TRUE FALSE TRUE TRUE


In [40]:
## Indicando nombre después de "$" y luego asignando
l3$values_lgl2 <- c(T,F,T,T)


In [41]:
str(l3)

List of 10
 $ num        : int [1:5] 1 2 3 4 5
 $ letra      : chr "X"
 $ pl         : chr [1:3] "hola" "buenas" "noches"
 $ matriz     : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista      :List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...
 $ n1         : int [1:4] 1 2 3 4
 $ n2         : chr "X"
 $ n3         : int [1:2, 1:2] 1 0 0 2
 $ values_lgl : logi [1:4] TRUE FALSE TRUE TRUE
 $ values_lgl2: logi [1:4] TRUE FALSE TRUE TRUE


In [44]:
# podemos modificar elementos dentro de un slot
# Ejemplo: Cambiar el último TRUE por un FALSE, en values_lgl2

l3[["values_lgl2"]][4] <- F


In [45]:
l3

$num
[1] 1 2 3 4 5

$letra
[1] "X"

$pl
[1] "hola"   "buenas" "noches"

$matriz
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$lista
$lista$a
[1] "2025-07-09"

$lista$b
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"


$n1
[1] 1 2 3 4

$n2
[1] "X"

$n3
     [,1] [,2]
[1,]    1    0
[2,]    0    2

$values_lgl
[1]  TRUE FALSE  TRUE  TRUE

$values_lgl2
[1]  TRUE FALSE  TRUE FALSE

In [47]:
l3$lista[[2]]

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [49]:
l3[[5]]$b

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [50]:
str(l3)

List of 10
 $ num        : int [1:5] 1 2 3 4 5
 $ letra      : chr "X"
 $ pl         : chr [1:3] "hola" "buenas" "noches"
 $ matriz     : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista      :List of 2
  ..$ a: Date[1:1], format: "2025-07-09"
  ..$ b: chr [1:26] "A" "B" "C" "D" ...
 $ n1         : int [1:4] 1 2 3 4
 $ n2         : chr "X"
 $ n3         : int [1:2, 1:2] 1 0 0 2
 $ values_lgl : logi [1:4] TRUE FALSE TRUE TRUE
 $ values_lgl2: logi [1:4] TRUE FALSE TRUE FALSE


### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí.

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.

 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [58]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(10,20,30)

df <- data.frame(id = c(10,20,30),
                 nombre = c("Miguel", "Rodrigo", "Sol"),
                 edad = c(36,30, 25))


In [52]:
class(df)

[1] "data.frame"

In [59]:
str(df)

'data.frame':	3 obs. of  3 variables:
 $ id    : num  10 20 30
 $ nombre: chr  "Miguel" "Rodrigo" "Sol"
 $ edad  : num  36 30 25


In [54]:
dim(df)

[1] 3 3

In [60]:
rownames(df)# ojo que no tiene nombres, pero por defecto nos retorna el vector con el número de fila.

[1] "1" "2" "3"

In [57]:
colnames(df)
names(df)

[1] "id"     "nombre" "edad"

[1] "id"     "nombre" "edad"

In [61]:
df

id nombre  edad
1 10 Miguel  36  
2 20 Rodrigo 30  
3 30 Sol     25

In [64]:
# Acceso a columnas de un data.frame
## Igual que en una lista
df$nombre
df[["nombre"]]
df[[2]]

[1] "Miguel"  "Rodrigo" "Sol"

[1] "Miguel"  "Rodrigo" "Sol"

[1] "Miguel"  "Rodrigo" "Sol"

In [66]:
# OJO:
df["nombre"] # Replica el comportamiento en listas, es decir, esto retorna un dataframe con el vector (objeto)
df[2]

nombre 
1 Miguel 
2 Rodrigo
3 Sol

nombre 
1 Miguel 
2 Rodrigo
3 Sol

In [68]:
df

id nombre  edad
1 10 Miguel  36  
2 20 Rodrigo 30  
3 30 Sol     25

In [69]:
##  Ganamos acceso como matriz
# segunda fila de df
df[2,]

# segunda columna y segunda fila
df[2,"nombre"]
df[2,2]



id nombre  edad
2 20 Rodrigo 30

[1] "Rodrigo"

[1] "Rodrigo"

In [71]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
df$tiene_mascota <- c(F,T,F)


In [72]:
df

id nombre  edad tiene_mascota
1 10 Miguel  36   FALSE        
2 20 Rodrigo 30    TRUE        
3 30 Sol     25   FALSE

In [73]:
df[["nacionalidad"]] <- "CL"

In [74]:
df

id nombre  edad tiene_mascota nacionalidad
1 10 Miguel  36   FALSE         CL          
2 20 Rodrigo 30    TRUE         CL          
3 30 Sol     25   FALSE         CL

In [75]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3
# Pensamos como si el objeto fuese una matriz
df[,c(1,3)]
df[,c("id","nombre")]# Referenciando el nombre de las columnas



id edad
1 10 36  
2 20 30  
3 30 25

id nombre 
1 10 Miguel 
2 20 Rodrigo
3 30 Sol

In [76]:
# Pensando como si el objeto fuese una lista
df[c(1,3)]
df[c("id","nombre")]

id edad
1 10 36  
2 20 30  
3 30 25

id nombre 
1 10 Miguel 
2 20 Rodrigo
3 30 Sol

In [79]:
# Consultas
df$edad >= 30

[1]  TRUE  TRUE FALSE

In [80]:
df[df$edad >= 30,]

id nombre  edad tiene_mascota nacionalidad
1 10 Miguel  36   FALSE         CL          
2 20 Rodrigo 30    TRUE         CL

In [81]:
df[["edad"]] >= 30

[1]  TRUE  TRUE FALSE

In [82]:
# Son equivalentes
df[df$edad >= 30,]
df[df[["edad"]] >= 30,]

id nombre  edad tiene_mascota nacionalidad
1 10 Miguel  36   FALSE         CL          
2 20 Rodrigo 30    TRUE         CL

id nombre  edad tiene_mascota nacionalidad
1 10 Miguel  36   FALSE         CL          
2 20 Rodrigo 30    TRUE         CL

In [83]:
# los registros con edad mayor o igual a 30 y que tengan mascota.
df[df$edad >= 30 & df$tiene_mascota == TRUE ,]

id nombre  edad tiene_mascota nacionalidad
2 20 Rodrigo 30   TRUE          CL

In [84]:
df[df$edad >= 30 & df$tiene_mascota ,]

id nombre  edad tiene_mascota nacionalidad
2 20 Rodrigo 30   TRUE          CL

In [85]:
df[df[["edad"]] >= 30 & df[["tiene_mascota"]] == TRUE ,]

id nombre  edad tiene_mascota nacionalidad
2 20 Rodrigo 30   TRUE          CL

In [86]:
df[df[["edad"]] >= 30 & df$tiene_mascota == TRUE ,]

id nombre  edad tiene_mascota nacionalidad
2 20 Rodrigo 30   TRUE          CL